# 실습 WEEK5: 배열

:::{admonition} 안내
:class: info  

- 실습 문제는 사전, 도전, 완전 실습 문제로 구성되어 있습니다.
- 사전 실습 문제는 수업 전에 미리 풀어보시면 도움이 됩니다.
- **<font color='blue'>도전 실습 문제는 etl>우리강좌>코딩수업>에 접속한 후, 해당 주차 문제의 소스코드를 제출하여 테스트를 통과해야 과제 점수를 받을 수 있습니다.</font>**
- **<font color='red'>제출기한은 실습수업시간부터 다음 실습수업 전날 자정까지</font>**입니다.
- 완전 실습 문제는 보너스 실습 문제로 생각하시면 됩니다.  도전 실습 문제를 다 풀어본 학생들이 추가적으로 풀어보시면 도움이 됩니다.
- 사전 실습 문제와 완전 실습 문제는 수업 시간에 별도 풀이를 하지 않습니다.
- 질문은 사전, 도전, 완전 그리고 수업과 관련된 모든 것에  대하여 교수자 or 조교 or 튜터에게 하시면 됩니다.
- **<font color='red'>가독성을 위해 입출력 데이터에서 콜론(:) 다음에는 항상 한칸 공백이 있습니다.</font>**

:::

### 데이터 입력과 출력 예
😄문자열을 입력받아 출력하시오.

---

<font color='blue'>`test case-1`</font>

Input Sample
```
즐거워
```
Output Sample
```
문자열:
출력결과: 즐거워
```


<font color='blue'>`test case-2`</font>

Input Sample
```
Say! I can do it!
```
Output Sample
```
문자열:
출력결과: Say! I can do it!
```

In [ ]:
input_data = input('문자열: ')
print(f'출력결과: {input_data}')

문자열: Say! I can do it!
출력결과: Say! I can do it!


## [도전 실습 문제]

- 1차원 배열부터 만들어보자.
- numpy모듈에서는 배열을 생성하는 다양한 방법을 지원한다.
  - numpy 모듈의 `array()`를 통해 배열을 만들 수 있다.
  - numpy 모듈의 `arange()`를 통해 배열을 만들 수 있다.


```
np.array(리스트 or range())
np.arange(start, end, step)
```



### (함께) Problem: 1차원 배열 생성하기
😄 출력결과와 같이 1차원 배열(array)를 생성해보세요.

```
np.array(리스트 or range()): numpy 모듈의 `array()`를 통해 배열 생성
np.arange(start, end, step): numpy 모듈의 `arange()`를 통해 배열 생성
```
---

<font color='blue'>`test case-1`</font>

Output Sample
```
1-D array: [10  8  5  7 19]
1-D array: [ 10  20  30  40  50  60  70  80  90 100]
```


### (함께) Problem: 2차원 배열 생성하기
😄 출력결과와 같이 2차원 배열(array)를 생성해보세요.

```
np.array([리스트 of 리스트]): 중첩 리스트로 배열 생성
np.arange(start,end,step).reshape(row, column): 1차원 배열 생성 후, reshape()을 통해서 모양 변경
- row는 행의 개수, column은 열의 개수. column을 -1로 써주면 각 행에 들어갈 데이터의 개수를 동일하게 적용해준다.
```

---

<font color='blue'>`test case-1`</font>

Output Sample
```
2-D array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
```


### (스스로) Problem: 3차원 배열 생성하기
😄 출력결과와 같이 3차원 배열(array)를 생성해보세요.

---

<font color='blue'>`test case-1`</font>

Output Sample
```
3-D array:
[[[100  90  80]
  [ 70  60  50]]

 [[ 15  25  35]
  [ 45  55  65]]

 [[ 11  22  33]
  [ 44  55  66]]]
```


### (함께)Problem: 실수형 랜덤 배열 생성하기1

😄 0이상 1미만의 임의의 실수값으로 채워진 3(면) x 3(행) x 2(열) 배열을 생성하여 배열의 모양과 함께 출력하시오.

- 0 ≤ 실수 < 1로 채우기: np.random.random((배열의 모양))
- 배열의 모양은 배열명.shape 으로 알 수 있다.
---

<font color='blue'>`test case-1`</font>

Output Sample
```
배열의 모양: (3, 3, 2)
[[[0.37376048 0.15396633]
  [0.96137267 0.55752608]
  [0.75176515 0.07312223]]

 [[0.42532833 0.57415501]
  [0.07496968 0.88594487]
  [0.28332782 0.2971798 ]]

 [[0.44362661 0.76007254]
  [0.27045252 0.35849775]
  [0.22908071 0.42359505]]]
```


### (함께) Problem: 실수형 랜덤 배열 생성하기2
😄 4.5이상 7미만의 임의의 실수값으로 채워진  4 x 2 x 2 배열을 생성하시오.

- a ≤ 실수 < b로 채우기: np.random.uniform(a, b, (배열의 모양))
---

<font color='blue'>`test case-1`</font>

Output Sample
```
배열의 모양: (4, 2, 2)
[[[6.3727774  5.33248683]
  [6.58527757 5.54165326]]

 [[5.22078554 5.65552663]
  [6.56711334 5.9770209 ]]

 [[6.9212381  6.58904435]
  [6.68180005 5.73738029]]

 [[5.30810951 5.83762379]
  [4.95383333 6.6055771 ]]]
```


### (스스로) Problem: 정수형 랜덤 배열 생성하기
😄 10이상 20미만의 임의의 정수로 채워진 3 x 2 x 5 배열을 생성하시오.
- a ≤ 정수 < b로 채우기: np.random.randint(a, b, (배열의 모양))
---

<font color='blue'>`test case-1`</font>

Output Sample
```
배열의 모양: (3, 2, 5)
[[[18 16 14 12 14]
  [18 14 12 16 10]]

 [[10 14 16 14 11]
  [16 10 18 13 14]]

 [[17 17 15 17 18]
  [12 16 11 18 17]]]
```


### (함께) Problem: 배열 인덱싱
😄 아래 배열에서 요소를 인덱싱 또는 슬라이싱 하세요.
```
[[[100 110 120]
  [130 140 150]]

 [[ 15  25  35]
  [ 45  55  65]]

 [[ 55  50  45]
  [ 40  35  30]]]
```
---
Output Sample
```
1: [130 140 150]
2: 55
3: [35  30]
4: [[[15 25 35]
  [45 55 65]]

 [[55 50 45]
  [40 35 30]]]
```

### (스스로) Problem: 배열을 상하 반전시키는 연산
😄 배열의 크기 N, M과 데이터를 입력받아 상하반전하여 출력하시오. 데이터는 한 줄에 한 행(예: 1 3 2 7 8 9)씩 들어온다.

- 2 ≤ N, M ≤ 100
- N, M은 짝수
- 1 ≤ $A_{ij}$ ≤ $10^8$

---

<font color='blue'>`test case-1`</font>
Input Sample
```
4 6
1 3 2 7 8 9
7 2 1 3 5 2
3 5 1 7 9 4
6 2 0 1 8 6
```

Output Sample
```
N M:
오리지날 데이타
[[1 3 2 7 8 9]
 [7 2 1 3 5 2]
 [3 5 1 7 9 4]
 [6 2 0 1 8 6]]
상하반전 후
[[6 2 0 1 8 6]
 [3 5 1 7 9 4]
 [7 2 1 3 5 2]
 [1 3 2 7 8 9]]

```

### (스스로) Problem: 성적총점과 각 과목 평균구하기
😄 Array를 이용하여 다음과 같이 실행되는 프로그램을 작성하시오.
학생 수가 먼저 입력되고 학생별 국,영,수 과목 성적이 콤마로 구분되어 차례대로 들어옵니다. 평균은 소수점 2자리까지 출력합니다.
- np.sum(배열명, axis): 합을 반환한다.
- np.mean(배열명, axis): 평균을 반환한다.
  - axis=0: 행
  - axis=1: 열
- numpy에서의 round()함수는 np.round(값, 소수점 자리수)와 같이 사용한다.
또는 array명.round(소수점 자리수)와 같이 사용한다.

---

<font color='blue'>`test case-1`</font>

Input Sample
```
3
50,60,80
80,70,90
70,80,80
```

Output Sample
```
학생 수:
1번째 학생 국,영,수:
2번째 학생 국,영,수:  
3번째 학생 국,영,수:  
학생들의 성적:
[[50 60 80]
 [80 70 90]
 [70 80 80]]
각 학생의 총점:
[190 240 230]
각 과목의 평균:
[66.67 70. 83.33]
```

## [완전 실습 문제]

### Problem: 가중치적용하여 성적구하기
😄 배열변수 scores에는 앞에서부터 번호, 국어, 영어, 수학, 체육, 컴기의 시험점수가 들어있습니다.

전체 평균점수가 가장 높은 학생 번호를 구하시오.

전체 평균점수가 가장 낮은 학생 번호를 구하시오.

국어, 영어, 수학 점수의 평균이 가장 높은 학생 번호를 구하시오.

국어, 영어, 수학 점수에 2배 가중치를 준다면 5과목의 평균 점수가 가장 높은 학생의 번호를 구하시오.



```
scores=np.array([[23231., 70., 85., 95., 100., 100.],
          [23232., 100., 84., 90., 90., 95.],   
          [23233., 95., 95., 80., 75., 75.],          
          [23234., 65., 75., 70., 90., 100.],
          [23235., 90., 80., 85., 95., 95.],          
          [23236., 90., 90., 95., 75., 80.],          
          [23237., 60., 90., 80., 40., 45.],          
          [23238., 85., 90., 75., 60., 90.],              
          [23239., 90., 85., 85., 90., 85.]])
```

---


<font color='blue'>`test case-1`</font>

Output Sample
```
전체 평균점수가 가장 높은 학생 번호:  23232
전체 평균점수가 가장 낮은 학생 번호:  23237
국,영,수 평균이 가장 높은 학생 번호:  23236
국,영,수 2배 가중치 평균이 가장 높은 학생 번호:  23232
```

In [ ]:
import numpy as np
scores=np.array([[23231., 70., 85., 95., 100., 100.],
          [23232., 100., 84., 90., 90., 95.],
          [23233., 95., 95., 80., 75., 75.],
          [23234., 65., 75., 70., 90., 100.],
          [23235., 90., 80., 85., 95., 95.],
          [23236., 90., 90., 95., 75., 80.],
          [23237., 60., 90., 80., 40., 45.],
          [23238., 85., 90., 75., 60., 90.],
          [23239., 90., 85., 85., 90., 85.]])